### ISSUE TITLE
Use ARC 0.0.1-rc.8

### ISSUE THREAD

**Issue by orenyodfat** [gnosis/dx-daostack#49]
Please use [arc 0.0.1-rc.8](https://www.npmjs.com/package/@daostack/arc/v/0.0.1-rc.8)

Please replace @daostack/arc.js with [@daostack/migration@0.0.1-rc.8](https://www.npmjs.com/package/@daostack/migration/v/0.0.1-rc.8-v1) package .
The migration.json should be fetch from this package (instead of arc.js)

This arc update might require some api changes.

**Comment by dkent600** [comment]
Note that v0.0.1-rc.8 of the migration repo does not contain v8 of the GenesisProtocol.

**Comment by orenyodfat** [comment]
Did I missed something here ?
It use Arc rc.8 which use infra "0.0.1-rc.9" which is ok.

**Comment by Velenir** [comment]
`@daostack/infra@0.0.1-rc.9` is indeed included as part of `@daostack/arc@0.0.1-rc.8` deps
if GenesisProtocol address is wrong/old we can hardcode it

**Comment by orenyodfat** [comment]
Seems like there is an issue with the migration.
I am checking this.

**Comment by ben-kaufman** [comment]
Package released. Please use `@daostack/migration@0.0.1-rc.8-v2`.

**Comment by DmitryBespalov** [comment]
Hi, I think I was mistakenly assigned to this issue

**Comment by Velenir** [comment]
Sorry about that :smiley:
