### ISSUE TITLE
Please remove contractold dir from this repo .

### ISSUE THREAD

**Issue by orenyodfat** [gnosis/dx-daostack#53]

**Comment by anxolin** [comment]
Done

**Comment by orenyodfat** [comment]
where it is done ?

**Comment by anxolin** [comment]
Same as all the other issues: https://github.com/gnosis/dx-daostack/tree/feature/prep_dao

Please close if it's not a blocker. Waiting for your approval to deploy.

**Comment by orenyodfat** [comment]
issues should be closed when it is merged into master.
master still have contractsOld

**Comment by anxolin** [comment]
Still waiting for your approval for merging..
