### ISSUE TITLE
please create env file for the dxDAO 

### ISSUE THREAD

**Issue by orenyodfat** [gnosis/dx-daostack#54]

**Comment by anxolin** [comment]
It's created, although it's using the defaults, that's the point. The deployment day should be done with no parameters, if possible: https://github.com/gnosis/dx-daostack/blob/feature/prep_dao/env_vars/dao.conf

Anyways, u can find explained where are the defaults.

For todays testrun, we do have a env var with some overrides: https://github.com/gnosis/dx-daostack/blob/feature/prep_dao/env_vars/19-02-06__mainnet_test.conf

**Comment by orenyodfat** [comment]
We need a env file for the real dxDAO . that we all agree and this repo will deploy it.

**Comment by anxolin** [comment]
That's the one I provided here: https://github.com/gnosis/dx-daostack/blob/feature/prep_dao/env_vars/dao.conf

Basically uses the defaults, and shows you were they are. You can override, but the idea is not to do that. Only for tests like the one of today.

Please close if it's not a blocker. Waiting for your approval to deploy.

**Comment by orenyodfat** [comment]
why not have a separate env file for the dxDAO ..with real dates and all ? this way we can review it now

**Comment by anxolin** [comment]
We can add the dates, it's fine. But we would be overriding the default to set the default values.
There's a lot of default values, do you want to add them all?

**Comment by anxolin** [comment]
Can we close this one?

**Comment by anxolin** [comment]
@orenyodfat this is the final file: https://github.com/gnosis/dx-daostack/blob/feature/agreement/env_vars/2019-05-29__dxDao_mainnet.conf

Let me know if this solves this issue
