### ISSUE TITLE
Move all deployment text and json files to a directory 

### ISSUE THREAD

**Issue by orenyodfat** [gnosis/dx-daostack#55]
The directory can be called deployment_logs (or something)

**Comment by anxolin** [comment]
done https://github.com/gnosis/dx-daostack/blob/feature/prep_dao/deployement_logs

**Comment by orenyodfat** [comment]
I do not see that on master branch .

**Comment by anxolin** [comment]
Cause is not, this branch was to do the tests. It has the latest changes and the envs for the deployement. 

Please close if it's not a blocker. Waiting for your approval to deploy.

**Comment by orenyodfat** [comment]
please merge it to master
