### ISSUE TITLE
clean env files ..

### ISSUE THREAD

**Issue by orenyodfat** [gnosis/dx-daostack#57]
e.g 

remove 
FOUNDERS_INITIAL_TOKENS=100
FOUNDERS_INITIAL_REP=200

**Comment by anxolin** [comment]
Todays test run, doesn't have those ones

**Comment by orenyodfat** [comment]
Is that manifested on the master branch ?

**Comment by anxolin** [comment]
Yes in https://github.com/gnosis/dx-daostack/tree/feature/prep_dao, pls close if it's not a blocker. Waiting for your approval to deploy

**Comment by orenyodfat** [comment]
why not merge it to master?

**Comment by anxolin** [comment]
Because you are the approver of the PR, and u havent approve yet :)
